name: 'Manual'
on:
  workflow_dispatch:
    inputs:
      name:
       description: 'Name'
       type: string
       default: 'default value'
jobs:
  manual:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
        run: echo "Hello, ${{ inputs.name }}!"
